#!/usr/bin/env bash
# 从云上 Azure Container App (xiaoshou-api) 一比一拉取所有 env + secrets,
# 写入本地 .env (gitignored)。本地容器: PG/Redis 走 docker, 其他保持云端拟真。
# 前置: az login。
# 用法: bash scripts/sync_env_from_prod.sh
set -euo pipefail

RG="${RG:-sales-rg}"
APP="${APP:-xiaoshou-api}"
OUT="${OUT:-.env}"

echo "[1/3] 列云端 env keys..."
ENV_KEYS_RAW=$(az containerapp show -g "$RG" -n "$APP" \
  --query "properties.template.containers[0].env[].name" -o tsv)
# 兼容 macOS bash 3.2 (无 mapfile)
ENV_KEYS=()
while IFS= read -r line; do
  [ -n "$line" ] && ENV_KEYS+=("$line")
done <<< "$ENV_KEYS_RAW"

echo "[2/3] 写 $OUT (本地 PG/Redis + AUTH 覆写在最前, 云端 env 在后)..."
{
  echo "# Auto-generated by scripts/sync_env_from_prod.sh — DO NOT COMMIT"
  echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ) from Container App $APP"
  echo ""
  echo "# === Local override (PG/Redis 走容器, 关 AUTH) ==="
  echo "PG_HOST=postgres"
  echo "PG_USER=sales"
  echo "PG_PASSWORD=sales_dev_pw"
  echo "PG_DB=sales_system"
  echo "REDIS_HOST=redis"
  echo "REDIS_DB=0"
  echo "AUTH_ENABLED=false"
  echo ""
  echo "# === Mirrored from cloud ==="
  for k in "${ENV_KEYS[@]}"; do
    case "$k" in PG_*|REDIS_*|AUTH_ENABLED) continue ;; esac

    val=$(az containerapp show -g "$RG" -n "$APP" \
      --query "properties.template.containers[0].env[?name=='$k'].value | [0]" -o tsv 2>/dev/null)
    sec=$(az containerapp show -g "$RG" -n "$APP" \
      --query "properties.template.containers[0].env[?name=='$k'].secretRef | [0]" -o tsv 2>/dev/null)

    if [ -n "$sec" ] && [ "$sec" != "None" ]; then
      val=$(az containerapp secret show -g "$RG" -n "$APP" --secret-name "$sec" --query value -o tsv 2>/dev/null || echo "")
    fi

    if [ "$(printf '%s' "$val" | wc -l)" -gt 0 ]; then
      printf '%s="%s"\n' "$k" "$val"
    else
      printf '%s=%s\n' "$k" "$val"
    fi
  done
} > "$OUT"

echo "[3/3] 完成,写了 $(wc -l < "$OUT") 行。"
echo "下一步: docker compose up -d api"
